SELECT * FROM employees;
SELECT name FROM employees;
SELECT * FROM employees WHERE salary > 50000;
UPDATE employees SET salary = 60000 WHERE id = 3;
DELETE FROM employees WHERE id = 5;
SELECT * FROM employees LIMIT 10;
SELECT DISTINCT job_title FROM employees;
SELECT COUNT(*) FROM employees;
SELECT AVG(salary) FROM employees;
SELECT MAX(salary) FROM employees;
SELECT job_title, COUNT(*) FROM employees GROUP BY job_title;
SELECT * FROM employees e JOIN departments d ON e.department_id = d.id;
SELECT e.name, d.department_name FROM employees e JOIN departments d ON e.department_id = d.id;
SELECT * FROM employees WHERE hire_date > NOW() - INTERVAL '6 months';
CREATE TABLE projects (id SERIAL PRIMARY KEY, project_name VARCHAR(100), start_date DATE);
INSERT INTO projects (project_name, start_date) VALUES ('New Project', '2023-08-01');
SELECT * FROM projects WHERE start_date > '2023-01-01';
UPDATE projects SET project_name = 'Updated Project' WHERE id = 2;
DELETE FROM projects WHERE start_date < '2022-01-01';
DROP TABLE projects;